openapi: 3.0.0
info:
  title: Kontokorrent
  version: 1.0.0
security:
  - bearerAuth: []
servers:
  - url: 'https://kontokorrent.marik.ch/api'
paths:
  /token:
    post:
      summary: einen Bearer Token abholen für die Authorizaton der restlichen api
      tags:
        - token
      security: []
      requestBody:
        description: Tokenrequest
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRequest'
      responses:
        '200':
          description: Tokenresponse
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Token'
        '400':
          description: secret fehlt
        '401':
          description: es gibt keinen Kontokorrent mit diesem Secret
  /kontokorrent:
    get:
      summary: akuteller Status des Kontokorrents
      tags:
        - Kontokorrent
      responses:
        '200':
          description: der aktuelle Stand des Kontokorrents
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Kontokorrent'
    post:
      summary: einen neuen Kontokorrent anlegen
      tags:
        - Kontokorrent
      security: []
      requestBody:
        description: Kontokorrent der angelegt werden soll
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NeuerKontokorrent'
      responses:
        '200':
          description: erfolgreich angelegt
        '400':
          description: secret fehlt oder wird bereits verwendet
  /persons:
    post:
      summary: eine Person anlegen
      tags:
        - Personen
      requestBody:
        description: Person die angelegt werden soll
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NeuePerson'
      responses:
        '200':
          description: Die angelegte Person
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Person'
        '400':
          description: name nicht mehr verfügbar oder nicht angegeben
    delete:
      summary: eine Person löschen
      tags:
        - Personen
      parameters:
        - name: id
          in: path
          description: id der Person die gelöscht werden soll
          required: true
          schema:
            type: string
      responses:
        '200':
          description: wurde gelöscht
        '400':
          description: id fehlt
        '404':
          description: Person nicht gefunden
  /payments:
    get:
      summary: alle Bezahlungen auflisten
      tags:
        - Bezahlungen
      responses:
        '200':
          description: Ein Array von Bezahlungen
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bezahlungen'
    post:
      summary: eine neue Bezahlung anlegen
      tags:
        - Bezahlungen
      requestBody:
        description: Bezahlung die angelegt werden soll
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NeueBezahlung'
      responses:
        '200':
          description: Bezahlung
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bezahlung'
        '400':
          description: 'bezahlender, empfaenger oder wert nicht angegeben'
        '404':
          description: bezahlender oder empfaenger nicht gefunden
    put:
      summary: eine Bezahlung bearbeiten
      tags:
        - Bezahlungen
      parameters:
          - name: id
            in: path
            description: id der Bezahlung die geändert werden soll
            required: true
            schema:
              type: string
      requestBody:
        description: Geänderte Bezahlung
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GeaenderteBezahlung'
      responses:
        '200':
          description: Bezahlung
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Bezahlung'
        '400':
          description: 'empfaenger wert oder zeitpunkt nicht angegeben, empfaenger nicht gefunden'
        '404':
          description: bezahlung oder empfaenger nicht gefunden
    delete:
      summary: eine Bezahlung löschen
      tags:
        - Bezahlungen
      parameters:
        - name: id
          in: path
          description: id der Bezahlung die gelöscht werden soll
          required: true
          schema:
            type: string
      responses:
        '200':
          description: wurde gelöscht
        '400':
          description: id fehlt
        '404':
          description: Bezahlung nicht gefunden
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    Token:
      properties:
        token:
          type: string
    TokenRequest:
      required:
        - secret
      properties:
        secret:
          type: string
    NeuerKontokorrent:
      required:
        - secret
      properties:
        secret:
          type: string
    Kontokorrent:
      properties:
        personenStatus:
          type: array
          items:
            $ref: '#/components/schemas/PersonenStatus'
        letzteBezahlungen:
          type: array
          items:
            $ref: '#/components/schemas/Bezahlung'
    PersonenStatus:
      properties:
        person:
          $ref: '#/components/schemas/Person'
        wert:
          type: number
          description: >-
            Gesamtsaldo also alles was noch bezahlt werden muss minus alles was
            man noch bekommt. Ein positiver Wert bedeutet somit Schulden
    Saldo:
      properties:
        betrifft:
          $ref: '#/components/schemas/Person'
        saldo:
          type: number
          description: >-
            ein positiver Wert bedeutet man schuldet der Person _betrifft_
            diesen Betrag, ein negativer Wert bedeutet man bekommt diesen Betrag
            von der jeweiligen Person
    Person:
      properties:
        name:
          type: string
        id:
          type: string
    NeuePerson:
      required:
        - name
      properties:
        name:
          type: string
    NeueBezahlung:
      required:
        - bezahlendePerson
        - empfaenger
        - wert
      properties:
        bezahlendePerson:
          type: string
          description: id der Person die bezahlt
        empfaenger:
          type: array
          items:
            type: string
            description: ids der Personen an die die Zahlung geht
        wert:
          type: number
        beschreibung:
          type: string
        zeitpunkt:
          type: string
          format: date-time
    GeaenderteBezahlung:
      required:
        - empfaenger
        - wert
        - zeitpunkt
      properties:
        empfaenger:
          type: array
          items:
            type: string
            description: ids der Personen an die die Zahlung geht
        wert:
          type: number
        beschreibung:
          type: string
        zeitpunkt:
          type: string
          format: date-time
    Bezahlung:
      properties:
        id:
          type: string
        zeitpunkt:
          type: string
          format: date-time
        bezahlendePerson:
          $ref: '#/components/schemas/Person'
        empfaenger:
          type: array
          items:
            $ref: '#/components/schemas/Person'
        wert:
          type: number
        beschreibung:
          type: string
    Bezahlungen:
      type: array
      items:
        $ref: '#/components/schemas/Bezahlung'
